name: BiomeGrowth
version: 1.0.0-1
main: me.camdaloon.biomegrowth.BiomeGrowthPlugin
api-version: '1.21'
author: camdaloon
description: Customize plant growth speed per biome.
commands:
  plantspeedset:
    description: Set the growth speed for a plant in a biome.
    usage: /plantspeedset <plantname> <biomename> <speed>
    permission: biomegrowth.set
    aliases: [pss]
permissions:
  biomegrowth.set:
    description: Allows changing plant growth speeds.
    default: op
