name: BiomeGrowth
version: 1.0.1-1_beta
main: me.camdaloon.biomegrowth.BiomeGrowthPlugin
api-version: '1.21'
author: camdaloon
description: Customize plant growth speed per biome.
commands:
  plantspeedset:
    description: Set the growth speed for a plant in a biome.
    usage: /plantspeedset <plantname> <biomename> <speed>
    permission: biomegrowth.set
    aliases: [pss]
  plantspeedinfo:
    description: Show the configured growth speed for a plant in a biome.
    usage: /plantspeedinfo <plantname> <biomename>
    permission: biomegrowth.set
    aliases: [psi]
permissions:
  biomegrowth.set:
    description: Allows changing and viewing plant growth speeds.
    default: op
